# -*- coding: utf-8 -*-
"""Task-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6of66kKmlY4RhIKMQmaeC4yg45olQ9h
"""

#install dependencies
!pip install markovify

#importing libraries
import pandas as pd
import markovify

# Read text file where each line is a headline
with open('/content/drive/MyDrive/Dataset/sonnets.txt', 'r', encoding='utf-8') as file:
    lines = file.readlines()

# Remove any trailing newlines or whitespace
headlines = [line.strip() for line in lines]

# Preview first 5 headlines
for line in headlines[:5]:
    print(line)

text_model = markovify.NewlineText(lines,state_size=2)

for i in range(5):
  print(text_model.make_sentence())

text_model1 = markovify.NewlineText(lines,state_size = 2)
text_model2 = markovify.NewlineText(lines,state_size = 2)

for i in range(5):
    print(text_model1.make_sentence())

#text generation using markov chains
for i in range(10):
    temp = text_model2.make_sentence()
    if temp is not None:
        print(temp)